import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {rooms,walls,furniture,roomAt,walkable,pathfind,planSVG} from './layout.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={room:'all',full:false,top:false,person:0,walk:false,time:15,weather:'sunny',routine:'auto',focus:false};
const visibleRooms=rooms.filter(r=>!r.hidden),roomGroups=new Map(),objects=new Map(),wallMeshes=[],clickables=[],lights=[];
let renderer,scene,camera,controls,sun,ambient,moon,rain,elapsed=0,toastTimer,raf;
const mats=new Map();
function mat(color,options={}){let k=color+JSON.stringify(options);if(!mats.has(k))mats.set(k,new THREE.MeshStandardMaterial({color,roughness:.8,...options}));return mats.get(k)}
function box(g,x,y,z,w,h,d,color,round=.03){const mesh=new THREE.Mesh(round?new RoundedBoxGeometry(w,h,d,2,Math.min(round,w/3,h/3,d/3)):new THREE.BoxGeometry(w,h,d),typeof color==='string'?mat(color):color);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh}
function sphere(g,x,y,z,r,color,sx=1,sy=1,sz=1){const mesh=new THREE.Mesh(new THREE.SphereGeometry(r,16,12),mat(color));mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);mesh.castShadow=true;g.add(mesh);return mesh}
function cylinder(g,x,y,z,r,h,color,r2=r){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r2,h,24),mat(color));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;g.add(mesh);return mesh}
function init(){scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.1,150);try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch(e){$('#fallback').hidden=false;return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;$('#canvas-wrap').appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI*.47;controls.minDistance=3;controls.maxDistance=80;controls.enablePan=true;
ambient=new THREE.HemisphereLight('#fff7dc','#acb9a0',2.1);scene.add(ambient);sun=new THREE.DirectionalLight('#fff0cf',3.4);sun.position.set(-5,15,-2);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-13,right:13,top:15,bottom:-15,near:.5,far:50});sun.shadow.bias=-.0004;sun.shadow.normalBias=.03;sun.target.position.set(3,0,7);scene.add(sun,sun.target);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.13}));ground.rotation.x=-Math.PI/2;ground.position.set(4,-.38,7);ground.receiveShadow=true;scene.add(ground);
for(const r of rooms){const group=new THREE.Group();group.userData.room=r.id;roomGroups.set(r.id,group);scene.add(group);const[x,z,w,d]=r.rect;box(group,x+w/2,-.18,z+d/2,w,.34,d,'#d8d0bb',.06);box(group,x+w/2,.005,z+d/2,w-.03,.06,d-.03,r.color,.015);if(r.kind==='tile'){for(let xx=x+.05;xx<x+w;xx+=.48)box(group,xx,.039,z+d/2,.008,.003,d-.03,'#eef0e4',0);for(let zz=z+.05;zz<z+d;zz+=.48)box(group,x+w/2,.039,zz,w-.03,.003,.008,'#eef0e4',0)}else{for(let xx=x+.2;xx<x+w;xx+=.22)box(group,xx,.039,z+d/2,.006,.003,d-.03,'#c9b799',0);for(let zz=z+.8;zz<z+d;zz+=.85){for(let xx=x+.1;xx<x+w-.1;xx+=.44)box(group,xx,.04,zz,.21,.002,.005,'#d2bf9e',0)}}
const light=new THREE.PointLight('#ffe5ac',0,6,2);light.visible=false;light.castShadow=false;light.shadow.mapSize.set(256,256);light.position.set(x+w/2,2.25,z+d/2);group.add(light);lights.push({room:r.id,light,on:false});if(!r.hidden){const fixture=cylinder(group,x+w/2,.11,z+d/2,.15,.03,'#ede4c7');fixture.visible=false}}
buildWalls();for(const f of furniture)buildFurniture(f);for(const r of visibleRooms){const btn=document.createElement('button');btn.className='room-label';btn.textContent=r.name;btn.dataset.room=r.id;btn.onclick=()=>selectRoom(r.id);$('#labels').append(btn)}
moon=sphere(scene,10,6,-2,.45,'#f8ecbc');moon.material=mat('#f8ecbc',{emissive:'#f3d99c',emissiveIntensity:1});moon.visible=false;
const points=[];for(let i=0;i<500;i++){const x=-3+Math.random()*15,z=-3+Math.random()*21;if(!roomAt(x,z))points.push(x,Math.random()*8,z)}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.Float32BufferAttribute(points,3));rain=new THREE.Points(rg,new THREE.PointsMaterial({color:'#8ea9b6',size:.045,transparent:true,opacity:.65}));scene.add(rain);rain.visible=false;
makePeople();setupCanvas();new ResizeObserver(()=>{resize();frameCamera()}).observe($('#canvas-wrap'));resize();frameCamera();applyLight();animate();}
function buildWalls(){for(const w of walls){const dx=w.b[0]-w.a[0],dz=w.b[1]-w.a[1],len=Math.hypot(dx,dz);let cursor=0;const part=(a,b,y,h,kind='wall')=>{if(b-a<.005)return;const g=new THREE.Group();scene.add(g);const mesh=box(g,w.a[0]+dx/len*(a+b)/2,y,w.a[1]+dz/len*(a+b)/2,dx?b-a:.13,h,dz?b-a:.13,kind==='glass'?mat('#b5d4d2',{transparent:true,opacity:.2,depthWrite:false}):kind==='frame'?'#c6b796':'#f1ebd9',.018);wallMeshes.push({mesh,group:g,w,kind,y,h});if(kind==='wall'&&y<1)box(g,mesh.position.x,.12,mesh.position.z,dx?b-a:.145,.12,dz?b-a:.145,'#c8bb9d',.012);return mesh};for(const o of w.open){part(cursor,o.from,1.36,2.72);if(o.type==='window'){part(o.from,o.to,.44,.88);part(o.from,o.to,2.52,.4);part(o.from,o.to,1.65,1.4,'glass');part(o.from,o.to,.91,.06,'frame');part(o.from,o.to,2.29,.06,'frame');part((o.from+o.to)/2-.025,(o.from+o.to)/2+.025,1.6,1.4,'frame')}else{part(o.from,o.to,2.49,.46);const g=new THREE.Group();scene.add(g);const threshold=box(g,w.a[0]+dx/len*(o.from+o.to)/2,.045,w.a[1]+dz/len*(o.from+o.to)/2,dx?o.to-o.from:.16,.015,dz?o.to-o.from:.16,'#bfa984',0);wallMeshes.push({mesh:threshold,group:g,w,kind:'threshold',y:.045,h:.015})}cursor=o.to}part(cursor,len,1.36,2.72)}updateWalls()}
function buildFurniture(f){const g=new THREE.Group();g.position.set(f.x,0,f.z);g.userData.furniture=f.id;roomGroups.get(f.room).add(g);const w=f.w,d=f.d,wood='#c5a57b',cream='#f3ebd7',dark='#797d63';let anim=[];const B=(x,y,z,ww,h,dd,c,r)=>box(g,x,y,z,ww,h,dd,c,r),C=(x,y,z,r,h,c)=>cylinder(g,x,y,z,r,h,c),S=(x,y,z,r,c,sx,sy,sz)=>sphere(g,x,y,z,r,c,sx,sy,sz);
if(f.type==='bed'){B(0,.21,0,w,.3,d,wood,.07);B(0,.43,0,w-.07,.22,d-.06,'#fff5e7',.1);const side=f.head==='right'?1:-1;B(side*(w/2-.04),.63,0,.1,.88,d+.04,wood,.04);B(-side*.25,.56,0,w-.68,.18,d-.04,f.tone,.09);for(const zz of [-d*.255,d*.255])B(side*(w/2-.37),.61,zz,.48,.16,d*.4,cream,.075);B(-side*.5,.65,0,.3,.045,d-.08,'#eee6cf',.02);for(let zz=-d/2+.13;zz<d/2;zz+=.14)B(-side*.5,.677,zz,.3,.007,.012,'#d0c5ae',0)}
else if(f.type==='wardrobe'){const h=1.64;B(0,.12,0,w,.15,d,wood);B(0,h/2, d/2-.04,w,h,.07,wood);for(const x of [-w/2+.035,w/2-.035])B(x,h/2,0,.07,h,d,wood);B(0,h,0,w,.08,d,wood);for(const y of [.2,.72,1.25])B(0,y,0,w-.07,.045,d-.05,'#e2ccb0');for(let i=0;i<3;i++){B(-w*.24+i*w*.22,.42,0,w*.16,.12,d*.6,['#abb794','#d2b5a1','#e7d59d'][i])}for(let i=0;i<2;i++){const panel=B(-w/4+i*w/2,.88,-d/2+.02,w/2-.015,1.48,.045,cream);const handle=box(panel,0,-.08,-.037,.025,.14,.025,'#9a8c64');anim.push({mesh:panel,base:panel.position.x,sign:i?1:-1})}}
else if(f.type==='sofa'){B(0,.19,0,w-.12,.22,d-.1,wood);B(0,.47,0,w,.47,d,'#bec7a8',.12);B(0,.78,d/2-.11,w,.66,.2,'#b3bf9d',.09);for(const x of [-w/2+.08,w/2-.08])B(x,.67,0,.16,.45,d,'#b3bf9d',.075);for(let i=-1;i<=1;i++)B(i*w*.3,.61,-.075,w*.285,.18,d*.62,'#c6d0b3',.07);const p=B(-w*.28,.81,.08,.41,.3,.15,'#f3e2b9',.07);p.rotation.z=.16;B(w*.29,.82,.07,.35,.33,.17,'#d0a18b',.06);B(.35,.71,-.1,.5,.025,.55,'#e8dfc3',.01)}
else if(f.type==='tv'){B(0,.2,0,w,.34,d,wood);for(let i=-1;i<=1;i++)B(i*w*.31,.23,-d/2-.01,w*.29,.22,.02,cream);B(0,.48,.01,.45,.04,.19,dark);B(0,.71,.02,.05,.45,.06,dark);B(0,1.01,0,w*.7,.87,.07,'#494f45',.04);const screen=B(0,1.02,-.045,w*.66,.78,.018,mat('#455d58',{emissive:'#7eaf9c',emissiveIntensity:.3}),.02);anim.push({screen});const art=new THREE.Group();art.position.set(0,1.03,-.06);g.add(art);sphere(art,-.28,.1,0,.11,'#f1d78e',1,1,.02);for(let i=0;i<3;i++){const mountain=new THREE.Mesh(new THREE.ConeGeometry(.31,.35+i*.06,3),mat(['#789c88','#9fb49a','#c3cba5'][i]));mountain.rotation.x=0;mountain.scale.z=.03;mountain.position.set(-.4+i*.4,-.15,0);art.add(mountain)}anim[0].art=art}
else if(f.type==='coffee'){C(0,.42,0,w/2,.11,wood);C(0,.2,0,.1,.35,'#a18b67');C(.13,.5,0,.07,.1,cream);B(-.1,.49,-.04,.18,.025,.23,'#8b9b78')}
else if(f.type==='side'){B(0,.3,0,w,.48,d,wood);B(0,.34,-d/2,.8*w,.19,.025,cream);if(f.interactive==='lamp'){C(0,.62,0,.1,.03,'#a89b77');C(0,.78,0,.018,.32,'#a89b77');const shade=cylinder(g,0,.97,0,.14,.2,cream,.18);const light=new THREE.PointLight('#ffdc89',0,2.8,2);light.castShadow=true;light.shadow.mapSize.set(256,256);light.position.set(0,.9,0);g.add(light);anim.push({light,shade})}}
else if(f.type==='desk'){B(0,.62,0,w,.09,d,wood);for(const x of [-w*.4,w*.4])B(x,.3,0,.055,.6,d*.85,wood);B(0,.69,0,.28,.025,.25,'#e7debf');B(0,.82,.1,.24,.24,.03,'#aeba98');C(.49,.23,-.03,.17,.4,cream)}
else if(f.type==='table'){B(0,.68,0,w,.11,d,wood,.08);for(const x of [-w*.38,w*.38])for(const z of [-d*.36,d*.36])B(x,.33,z,.055,.65,.055,wood);for(const z of [-d*.76,d*.76])for(const x of [-w*.28,w*.28]){B(x,.38,z,.38,.09,.36,'#b2bea0',.05);B(x,.59,z+Math.sign(z)*.15,.38,.4,.07,'#b2bea0',.05);for(const dx of [-.13,.13])B(x+dx,.17,z,.045,.34,.045,wood)}C(0,.79,0,.11,.16,'#d7b490');S(0,.99,0,.12,'#819464',1,1.4,1)}
else if(f.type==='plant'){cylinder(g,0,.22,0,.19,.36,'#d4b18d',.13);C(0,.51,0,.025,.6,'#8b9067');for(let i=0;i<8;i++){const a=i*2.4;const leaf=S(Math.cos(a)*.15,.6+i*.055,Math.sin(a)*.15,.12,i%2?'#95a378':'#7e9568',1,1.6,.55);leaf.rotation.z=Math.sin(a)*.8}}
else if(f.type==='cabinet'||f.type==='counter'){B(0,.44,0,w,.82,d,wood);B(0,.89,0,w+.015,.06,d+.015,cream);for(let i=0;i<Math.ceil(d/.6);i++)B(w/2+.005,.5,-d/2+(i+.5)*d/Math.ceil(d/.6),.015,.58,d/Math.ceil(d/.6)-.04,'#e0d8bd');if(f.type==='counter'){for(const zz of [-.45,.12]){C(0,.934,zz,.18,.02,'#515a4e');C(0,.95,zz,.12,.015,'#88917c')}B(0,.97,.73,.28,.035,.29,'#ad9e7a')}}
else if(f.type==='sink'){B(0,.42,0,w,.78,d,'#c4ccba');B(0,.84,0,w+.03,.07,d+.03,cream);B(0,.88,0,w*.7,.03,d*.63,'#8bada8',.045);B(w*.3,1.03,d*.24,.035,.28,.035,'#a4aea2');B(w*.18,1.17,d*.24,w*.25,.035,.035,'#a4aea2')}
else if(f.type==='fridge'){B(0,.93,0,w,1.8,d,'#e8e8d9',.06);B(w/2+.015,.7,0,.03,1.15,d-.04,'#f7f4e5');B(w/2+.015,1.53,0,.03,.47,d-.04,'#f7f4e5');B(w/2+.04,1.11,-.17,.035,.25,.035,'#919b89')}
else if(f.type==='toilet'){S(0,.27,-.04,w/2,cream,1,1.1,1.35);C(0,.44,-.1,w*.45,.075,'#fcfbef');C(0,.483,-.1,w*.27,.01,'#adc7be');B(0,.59,d*.28,w*.87,.6,.17,cream,.055)}
else if(f.type==='shower'){B(0,.075,0,w,.05,d,'#dde7df');B(w*.25,1.22,d*.3,.025,1.65,.025,'#919f95');C(w*.25,2.05,d*.16,.11,.035,'#919f95');B(-w/2,1,0,.02,1.9,d,mat('#a9cecb',{transparent:true,opacity:.2}),0)}
else if(f.type==='cushion'){B(0,.25,0,w,.35,d,'#b8c6a4',.1);B(-.4,.47,0,.4,.12,.38,cream,.07);B(.3,.46,0,.4,.1,.38,'#d7b5a0',.07)}
if(f.type==='tv'||(f.type==='wardrobe'&&['master','bed1'].includes(f.room)))g.rotation.y=Math.PI;
objects.set(f.id,{f,g,anim,on:false,value:0});if(f.interactive){g.traverse(m=>{if(m.isMesh){m.userData.object=f.id;clickables.push(m)}})}}
function updateWalls(){for(const item of wallMeshes){if(!item.original){item.original={x:item.mesh.position.x,z:item.mesh.position.z,w:item.mesh.geometry.parameters.width,d:item.mesh.geometry.parameters.depth}}const original=item.original,axis=item.w.a[0]===item.w.b[0]?'z':'x',cross=axis==='x'?'z':'x',len=axis==='x'?original.w:original.d;let lo=original[axis]-len/2,hi=original[axis]+len/2;const spans=rooms.filter(r=>roomVisible(r.id)).map(r=>{const[x,z,w,d]=r.rect;return axis==='x'?{min:x,max:x+w,cmin:z,cmax:z+d}:{min:z,max:z+d,cmin:x,cmax:x+w}}).filter(r=>original[cross]>=r.cmin-.08&&original[cross]<=r.cmax+.08&&r.max>lo+.001&&r.min<hi-.001);if(state.room!=='all'&&spans.length){lo=Math.max(lo,Math.min(...spans.map(r=>r.min)));hi=Math.min(hi,Math.max(...spans.map(r=>r.max)))}item.group.visible=state.room==='all'||spans.length>0;item.mesh.position[axis]=(lo+hi)/2;item.mesh.scale[axis]=(hi-lo)/len;for(const child of item.group.children){if(child!==item.mesh){child.position[axis]=(lo+hi)/2;child.scale[axis]=(hi-lo)/len}}const cut=!state.full;if(item.kind==='wall'){const low=item.y-item.h/2;const newH=cut?Math.max(0,Math.min(.64,low+item.h)-low):item.h;item.mesh.visible=newH>0;item.mesh.scale.y=newH/item.h;item.mesh.position.y=low+newH/2}else if(item.kind!=='threshold')item.mesh.visible=!cut;}}
function roomVisible(id){if(state.room==='all')return true;if(id===state.room)return true;const r=rooms.find(r=>r.id===id);return r?.parent===state.room}
function selectRoom(id){state.room=id;for(const [rid,g]of roomGroups)g.visible=roomVisible(rid);$('#view-title').textContent=id==='all'?'全屋漫游':rooms.find(r=>r.id===id).name;$('#view-description').textContent=id==='all'?'每一个小角落，都有生活的温度':'留一点时间，给这个温柔的角落';$$('#room-list button').forEach(b=>b.classList.toggle('active',b.dataset.room===id));if(id!=='all')$('#object-room').value=id;renderObjects();updateWalls();closePanel();frameCamera()}
function resize(){if(!renderer)return;const el=$('#canvas-wrap');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix()}
function frameCamera(){if(!camera)return;const bounds=new THREE.Box3();for(const r of rooms.filter(r=>roomVisible(r.id))){let[x,z,w,d]=r.rect;bounds.expandByPoint(new THREE.Vector3(x,0,z));bounds.expandByPoint(new THREE.Vector3(x+w,2.72,z+d))}const center=bounds.getCenter(new THREE.Vector3());center.y=.35;const size=bounds.getSize(new THREE.Vector3());const direction=state.top?new THREE.Vector3(0,1,.001):new THREE.Vector3(1.05,1.4,1.5).normalize();controls.target.copy(center);const corners=[];for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z])corners.push(new THREE.Vector3(x,y,z).sub(center));const right=new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),direction).normalize(),up=new THREE.Vector3().crossVectors(direction,right).normalize();let dist=0;const vf=Math.tan(THREE.MathUtils.degToRad(camera.fov/2)),hf=vf*camera.aspect;for(const c of corners)dist=Math.max(dist,Math.abs(c.dot(right))/(hf*.77)+c.dot(direction),Math.abs(c.dot(up))/(vf*.75)+c.dot(direction));camera.position.copy(center).addScaledVector(direction,dist);controls.update()}
const people=[];
function makePeople(){for(let i=0;i<2;i++){const g=new THREE.Group();scene.add(g);const skin='#f0c4a2',hair=i?'#634f42':'#695443',shirt=i?'#d4a28e':'#a7b28c';const legs=[];for(const x of [-.075,.075]){const leg=box(g,x,.15,0,.1,.24,.12,'#787d69',.04);box(leg,0,-.12,-.02,.12,.08,.18,'#e9debd');legs.push(leg)}cylinder(g,0,.42,0,.14,.28,shirt,i?.2:.14);sphere(g,0,.76,0,.205,skin,1,1.08,1);sphere(g,0,.87,.015,.205,hair,1,.7,1);for(const x of [-.065,.065])sphere(g,x,.78,-.181,.019,'#4b463c');for(const x of [-.13,.13])sphere(g,x,.72,-.15,.029,'#dda68d',1,.5,.25);for(const x of [-.19,.19]){const arm=box(g,x,.44,0,.08,.25,.09,skin,.04);arm.rotation.z=x>0?-.12:.12}if(i){for(const x of [-.2,.2])sphere(g,x,.76,.04,.09,hair,1,1.5,1);sphere(g,.19,.9,0,.045,'#d6b08b')}const ring=new THREE.Mesh(new THREE.RingGeometry(.21,.25,32),new THREE.MeshBasicMaterial({color:'#9baa75',transparent:true,opacity:.7,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.06;g.add(ring);g.position.set(i?3.2:2.7,0,i?5.5:5.1);people.push({g,legs,ring,path:[],activity:null,sitting:false,wait:4+i*4,idle:0,blocked:0,arrivals:0,manualUntil:0,status:'散步',home:[g.position.x,g.position.z]})}}
function commandPerson(index,target,activity=null,manual=true){const p=people[index];const origin=p.sitting?p.lastApproach:[p.g.position.x,p.g.position.z];const route=pathfind(origin,target);if(!route.length){if(manual)toast('这里暂时走不到，试试门口或空地吧');return false}if(p.sitting){p.releasing=true;p.releaseFrom=[p.g.position.x,p.g.position.z];p.releaseBlend=0;p.sitting=false}p.path=route;p.activity=activity;p.wait=0;p.blocked=0;p.status=activity?'走向'+activity.label:'散步';if(manual)p.manualUntil=elapsed+25;return true}
function toggleObject(id){const o=objects.get(id),f=o.f;if(f.interactive==='sit'||f.interactive==='study'){if(people.some((p,i)=>i!==state.person&&p.activity?.id===id)){toast('这里有人在用，稍后再来吧');return}if(commandPerson(state.person,f.approach,f))toast(`${state.person?'小桃':'阿木'}正走向${f.label}`);return}o.on=!o.on;toast(`${f.label}已${o.on?'打开':'关闭'}`);renderObjects()}
function roomLight(id){const l=lights.find(l=>l.room===id);l.on=!l.on;l.light.intensity=l.on?5:0;l.light.visible=l.on;lights.forEach(item=>item.light.castShadow=item.on&&lights.filter(v=>v.on).indexOf(item)<3);toast(`${rooms.find(r=>r.id===id).name}灯已${l.on?'打开':'关闭'}`);renderObjects()}
function renderObjects(){const id=$('#object-room').value;const l=lights.find(l=>l.room===id);$('#object-list').innerHTML=`<button data-light="${id}"><span>☼ 房间灯</span><em>${l?.on?'已开启':'已关闭'}</em></button>`+furniture.filter(f=>f.room===id&&f.interactive).map(f=>`<button data-object="${f.id}"><span>${f.label}</span><em>${['sit','study'].includes(f.interactive)?'走过去 →':objects.get(f.id)?.on?'已打开':'已关闭'}</em></button>`).join('');$$('[data-object]').forEach(b=>b.onclick=()=>toggleObject(b.dataset.object));$$('[data-light]').forEach(b=>b.onclick=()=>roomLight(b.dataset.light))}
function applyLight(){if(!sun)return;const t=state.time,day=Math.max(0,Math.sin((t-6)/12*Math.PI)),weather=state.weather==='sunny'?1:state.weather==='cloudy'?.65:.4;$('#stage').classList.toggle('night',day===0);ambient.intensity=.55+day*1.65*weather;sun.intensity=day*3.2*weather;sun.visible=day>0;sun.position.set(4+Math.cos((t-6)/12*Math.PI)*10,5+day*14,-3);sun.color.set(t>16||t<8?'#ffd3a0':'#fff1d7');renderer.toneMappingExposure=1.2;moon.visible=day===0&&state.weather==='sunny';rain.visible=state.weather==='rain';$('#stage').style.background=day===0?'radial-gradient(ellipse at 50% 45%,#727f82,#454f64)':state.weather==='rain'?'radial-gradient(ellipse at 50% 45%,#e4e9e3,#c7d2ce)':'radial-gradient(ellipse at 50% 45%,#f4f2e9,#e8eade)';const hour=Math.floor(t),minute=Math.floor((t-hour)*60);$('#clock-label').textContent=`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`;$('#weather-badge').innerHTML=`${day===0?'☾':state.weather==='sunny'?'☀':state.weather==='rain'?'☂':'☁'} <span>${day===0?'夜晚':t<10?'清晨':t<16?'午后':'黄昏'} · ${{sunny:'晴天',cloudy:'多云',rain:'雨天'}[state.weather]}</span>`}
let last=performance.now(),statusClock=0,random=Math.random;
function animate(forcedDt){const testing=typeof forcedDt==='number';if(!testing)raf=requestAnimationFrame(()=>animate());const now=performance.now(),dt=testing?forcedDt:Math.min(.05,(now-last)/1000);last=now;elapsed+=dt;controls.update();if($('#auto-time').checked){state.time=(state.time+dt*.025)%24;$('#time').value=state.time;applyLight()}for(const o of objects.values()){o.value=THREE.MathUtils.damp(o.value,o.on?1:0,6,dt);if(o.f.interactive==='wardrobe'){for(const a of o.anim){a.mesh.position.x=a.base+(a.sign<0?o.value*o.f.w*.48:0);a.mesh.position.z=-o.f.d/2+.02-(a.sign<0?.06*o.value:0)}}if(o.f.interactive==='tv'){o.anim[0].screen.material.emissiveIntensity=o.on?.9:0;o.anim[0].screen.material.color.set(o.on?'#83aaa0':'#45534e');o.anim[0].art.visible=o.on}if(o.f.interactive==='lamp'){o.anim[0].light.intensity=o.value*2.8;o.anim[0].light.visible=o.value>.002;o.anim[0].shade.material=o.on?mat('#ffe3a3',{emissive:'#ffd277',emissiveIntensity:.5}):mat('#f3ebd7')}}
for(let i=0;i<people.length;i++){const p=people[i],other=people[1-i];p.ring.visible=state.person===i;p.g.visible=roomVisible(roomAt(p.g.position.x,p.g.position.z)?.id);if(p.releasing){if(Math.hypot(p.lastApproach[0]-other.g.position.x,p.lastApproach[1]-other.g.position.z)>.36){p.releaseBlend=Math.min(1,p.releaseBlend+dt*2);const t=p.releaseBlend;p.g.position.x=THREE.MathUtils.lerp(p.releaseFrom[0],p.lastApproach[0],t);p.g.position.z=THREE.MathUtils.lerp(p.releaseFrom[1],p.lastApproach[1],t);p.g.position.y=.22*(1-t);if(t===1)p.releasing=false}continue}if(p.path.length){const next=p.path[0],v=new THREE.Vector2(next[0]-p.g.position.x,next[1]-p.g.position.z),dist=v.length(),speed=Math.min(dist,dt*.85);v.normalize();const nx=p.g.position.x+v.x*speed,nz=p.g.position.z+v.y*speed;const apart=Math.hypot(nx-other.g.position.x,nz-other.g.position.z);if(apart<.36){p.blocked+=dt;if(p.blocked>1.2&&(i===1||!other.path.length)){const candidates=[[.56,0],[-.56,0],[0,.56],[0,-.56]].map(([x,z])=>[p.g.position.x+x,p.g.position.z+z]).filter(q=>walkable(...q)&&Math.hypot(q[0]-other.g.position.x,q[1]-other.g.position.z)>.5);if(candidates.length){p.path=pathfind([p.g.position.x,p.g.position.z],candidates[0]);p.activity=null;p.wait=3;}else if(p.blocked>4){p.path=[];p.activity=null;p.wait=2;}p.blocked=0}}else{p.blocked=0;p.g.position.x=nx;p.g.position.z=nz;p.g.rotation.y=Math.atan2(-v.x,-v.y);p.legs[0].rotation.x=Math.sin(elapsed*10)*.35;p.legs[1].rotation.x=-Math.sin(elapsed*10)*.35;if(dist<.025)p.path.shift()}if(!p.path.length){p.arrivals++;p.wait=6;if(p.activity){p.lastApproach=p.activity.approach;p.sitting=true;p.status=p.activity.interactive==='study'?'学习中':'休息中';p.seatStart=[p.g.position.x,p.g.position.z];p.seatBlend=0}}}else{p.legs.forEach(l=>l.rotation.x=p.sitting?-1.2:0);if(p.sitting){p.seatBlend=Math.min(1,(p.seatBlend||0)+dt*2);const s=p.seatBlend*p.seatBlend*(3-2*p.seatBlend);p.g.position.x=THREE.MathUtils.lerp(p.seatStart[0],p.activity.seat[0],s);p.g.position.z=THREE.MathUtils.lerp(p.seatStart[1],p.activity.seat[1],s);p.g.position.y=.22*s;p.g.rotation.y=0}p.wait-=dt;if(p.wait<=0&&state.routine!=='manual'&&elapsed>p.manualUntil){const activities=furniture.filter(f=>f.approach&&!people.some(q=>q!==p&&q.activity?.id===f.id));let target;if(activities.length&&(state.routine==='schedule'||random()<.55)){const act=activities[state.routine==='schedule'?p.arrivals%activities.length:Math.floor(random()*activities.length)];commandPerson(i,act.approach,act,false)}else{const r=rooms[Math.floor(random()*rooms.length)], [x,z,w,d]=r.rect;target=[x+.2+random()*(w-.4),z+.2+random()*(d-.4)];commandPerson(i,target,null,false)}p.wait=3}}}
if(!testing)for(const label of $$('.room-label')){const r=rooms.find(r=>r.id===label.dataset.room),[x,z,w,d]=r.rect;const v=new THREE.Vector3(x+w*.5,.3,z+d*.72).project(camera);label.hidden=!roomVisible(r.id)||state.room!=='all'||v.z>1;label.style.left=(v.x*.5+.5)*$('#canvas-wrap').clientWidth+'px';label.style.top=(-v.y*.5+.5)*$('#canvas-wrap').clientHeight+'px'}if(rain.visible){const a=rain.geometry.attributes.position;for(let i=0;i<a.count;i++){a.setY(i,a.getY(i)-dt*5);if(a.getY(i)<0)a.setY(i,8)}a.needsUpdate=true}statusClock+=dt;if(statusClock>1){$('#people-status').textContent=people.map((p,i)=>`${i?'小桃':'阿木'}：${p.status}${elapsed<p.manualUntil?'（手动）':''}`).join(' · ');statusClock=0}if(!testing)renderer.render(scene,camera)}
function setupCanvas(){let start=null,multi=false,ids=new Set();const el=renderer.domElement;el.addEventListener('pointerdown',e=>{ids.add(e.pointerId);if(ids.size>1)multi=true;if(ids.size===1){start=[e.clientX,e.clientY];multi=false}});el.addEventListener('pointercancel',e=>{ids.delete(e.pointerId);start=null;multi=true});el.addEventListener('pointerup',e=>{ids.delete(e.pointerId);if(!start||multi||Math.hypot(e.clientX-start[0],e.clientY-start[1])>6){if(!ids.size)start=null;return}start=null;const bounds=el.getBoundingClientRect(),pointer=new THREE.Vector2((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(pointer,camera);const active=clickables.filter(m=>{let n=m;while(n){if(!n.visible)return false;n=n.parent}return true});const hits=ray.intersectObjects([...active,...wallMeshes.filter(w=>w.group.visible&&w.mesh.visible).map(w=>w.mesh)],false);if(!state.walk&&hits[0]?.object.userData.object){toggleObject(hits[0].object.userData.object);return}if(state.walk){const point=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-.05),point))commandPerson(state.person,[point.x,point.z]);}})}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800)}
function tab(id){$$('.tab-content').forEach(s=>s.hidden=s.id!==id);$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===id))}
function closePanel(){document.body.classList.remove('panel-open');$$('[data-panel]').forEach(b=>b.setAttribute('aria-expanded','false'))}
$('#room-list').innerHTML='<button data-room="all" class="active"><span class="icon">⌂</span><span>全屋漫游</span></button>'+visibleRooms.map(r=>`<button data-room="${r.id}"><span class="icon">${r.icon}</span>${r.name}</button>`).join('');$$('#room-list button').forEach(b=>b.onclick=()=>selectRoom(b.dataset.room));$('#object-room').innerHTML=visibleRooms.map(r=>`<option value="${r.id}">${r.name}</option>`).join('');$('#object-room').value='living';$('#object-room').onchange=renderObjects;$$('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-panel]').forEach(b=>b.onclick=()=>{const closing=document.body.classList.contains('panel-open')&&!$('#'+b.dataset.panel).hidden;closePanel();if(!closing){tab(b.dataset.panel);document.body.classList.add('panel-open');b.setAttribute('aria-expanded','true')}});$('#close-panel').onclick=()=>{closePanel();$('#mobile-nav button').focus()};$('#reset').onclick=()=>{state.top=false;frameCamera()};$('#top').onclick=()=>{state.top=!state.top;frameCamera()};$('#walls').onclick=()=>{state.full=!state.full;$('#walls span').textContent=state.full?'剖面看房':'完整墙体';$('#walls').setAttribute('aria-pressed',state.full);updateWalls()};$('#plan-svg').innerHTML=planSVG();const openPlan=()=>$('#plan-dialog').showModal();$('#plan').onclick=openPlan;$('#fallback-plan').onclick=openPlan;$('#evidence').onclick=()=>$('#evidence-dialog').showModal();$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([planSVG()],{type:'image/svg+xml;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='慢慢住-平面图.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};const focus=()=>{state.focus=!state.focus;document.body.classList.toggle('focus',state.focus);$('#unfocus').hidden=!state.focus;closePanel()};$('#focus').onclick=focus;$('#unfocus').onclick=focus;document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePanel();if(state.focus)focus()}});$$('[data-person]').forEach(b=>b.onclick=()=>{state.person=+b.dataset.person;$$('[data-person]').forEach(p=>p.classList.toggle('active',p===b));$('#walk').textContent=`◎ 点击地面，让${state.person?'小桃':'阿木'}走过去`});$('#walk').onclick=()=>{state.walk=!state.walk;$('#walk').classList.toggle('active',state.walk);$('#hint').textContent=state.walk?'行走模式 · 点击空地移动 · 可拖动旋转':'拖动旋转 · 滚轮缩放 · 点击家具互动';toast(state.walk?'点击房间里的空地，开始散步':'已退出行走模式');closePanel()};$('#routine').onchange=e=>state.routine=e.target.value;$('#time').oninput=e=>{state.time=+e.target.value;applyLight()};$$('[data-weather]').forEach(b=>b.onclick=()=>{state.weather=b.dataset.weather;$$('[data-weather]').forEach(p=>p.classList.toggle('active',p===b));applyLight()});init();renderObjects();
// Read-only diagnostics exposed for local verification.
window.home={state,people,objects,rooms,walkable,pathfind,renderer,scene,getCamera:()=>camera,selectRoom};

window.home.simulate=(seconds,seed)=>{let n=seed;random=()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296};let collisions=0,minSeparation=99,staticCollisions=0;const before=people.map(p=>p.arrivals);for(let i=0;i<seconds*30;i++){animate(1/30);const sep=people[0].g.position.distanceTo(people[1].g.position);minSeparation=Math.min(minSeparation,sep);if(sep<.3)collisions++;for(const p of people)if(!p.sitting&&!p.releasing&&!walkable(p.g.position.x,p.g.position.z,.14))staticCollisions++}random=Math.random;return {seed,seconds,arrivals:people.map((p,i)=>p.arrivals-before[i]),collisions,staticCollisions,minSeparation,status:people.map(p=>p.status)}};
